# Generated by Django 4.1.4 on 2022-12-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=4)),
                ('secao', models.CharField(max_length=4)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('on_line', models.BooleanField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
            ],
        ),
    ]
