# Generated by Django 4.1.4 on 2023-01-26 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_nascimento', models.DateField()),
                ('titulo_eleitor', models.CharField(max_length=12, unique=True)),
                ('zona', models.CharField(max_length=4)),
                ('secao', models.CharField(max_length=4)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('data_emissao', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Eleitores',
            },
        ),
        migrations.CreateModel(
            name='Politico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politico', models.CharField(max_length=100, unique=True)),
                ('foto', models.ImageField(unique=True, upload_to='')),
                ('partido', models.CharField(max_length=10)),
                ('num_partido', models.CharField(max_length=2)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Urna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=4)),
                ('secao', models.CharField(max_length=4)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('data_votacao', models.DateField(blank=True, default=None, null=True)),
                ('hora_inicio', models.TimeField(blank=True, default=None, null=True)),
                ('hora_fim', models.TimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleitores', to='urna.eleitor')),
                ('politico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='politicos', to='urna.politico')),
                ('urna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urnas', to='urna.urna')),
            ],
        ),
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.UniqueConstraint(fields=('zona', 'secao', 'municipio', 'uf'), name='urna_unica'),
        ),
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='hora_fim_maior'),
        ),
        migrations.AddField(
            model_name='politico',
            name='urna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='politicos', to='urna.urna'),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='urna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleitores', to='urna.urna'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('eleitor', 'cargo'), name='voto_unico'),
        ),
        migrations.AddConstraint(
            model_name='politico',
            constraint=models.UniqueConstraint(fields=('partido', 'num_partido', 'cargo'), name='cargo_unico'),
        ),
    ]
