# Generated by Django 4.1.4 on 2023-02-13 21:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_votacao', models.DateField(unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_nascimento', models.DateField()),
                ('titulo_eleitor', models.CharField(max_length=12, unique=True)),
                ('zona', models.CharField(max_length=4)),
                ('secao', models.CharField(max_length=4)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('data_emissao', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Eleitores',
            },
        ),
        migrations.CreateModel(
            name='Politico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politico', models.CharField(max_length=100, unique=True)),
                ('foto', models.ImageField(unique=True, upload_to='')),
                ('partido', models.CharField(max_length=10)),
                ('num_partido', models.CharField(max_length=2)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausentes', models.IntegerField()),
                ('votos_nulo', models.IntegerField()),
                ('votos_branco', models.IntegerField()),
                ('votos_invalidos', models.IntegerField()),
                ('votos_candidato_A', models.IntegerField()),
                ('votos_candidato_B', models.IntegerField()),
                ('votos_validos', models.IntegerField()),
                ('total_votos', models.IntegerField()),
                ('total_eleitores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Urna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=4)),
                ('secao', models.CharField(max_length=4)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('data_votacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.datavotacao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.eleitor')),
                ('politico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.politico')),
                ('urna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.urna')),
            ],
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.CheckConstraint(check=models.Q(('votos_invalidos', django.db.models.expressions.CombinedExpression(models.F('votos_branco'), '+', models.F('votos_nulo')))), name='total_invalidos'),
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.CheckConstraint(check=models.Q(('votos_validos', django.db.models.expressions.CombinedExpression(models.F('votos_candidato_A'), '+', models.F('votos_candidato_B')))), name='total_validos'),
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.CheckConstraint(check=models.Q(('total_votos', django.db.models.expressions.CombinedExpression(models.F('votos_validos'), '+', models.F('votos_invalidos')))), name='total_votos'),
        ),
        migrations.AddField(
            model_name='politico',
            name='urna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='politicos', to='urna.urna'),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='urna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleitores', to='urna.urna'),
        ),
        migrations.AddField(
            model_name='datavotacao',
            name='urna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datas', to='urna.urna'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('eleitor', 'data_votacao', 'cargo'), name='voto_unico'),
        ),
        migrations.AddConstraint(
            model_name='politico',
            constraint=models.UniqueConstraint(fields=('partido', 'num_partido', 'cargo'), name='cargo_unico'),
        ),
        migrations.AddConstraint(
            model_name='politico',
            constraint=models.UniqueConstraint(fields=('politico', 'partido', 'num_partido', 'cargo'), name='politico_unico'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao__gte', datetime.date(2023, 2, 13))), name='data_votacao_hoje'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__gte', datetime.time(21, 45, 45, 330956))), name='hora_inicio_agora'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='hora_fim_maior'),
        ),
    ]
