# Generated by Django 4.1.4 on 2023-01-27 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao', datetime.date(2023, 1, 27))), name='data-de-hoje'),
        ),
    ]
