# Generated by Django 4.1.4 on 2023-01-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='partido',
            field=models.CharField(max_length=5),
        ),
    ]
