# Generated by Django 4.1.4 on 2022-12-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urna',
            old_name='on_line',
            new_name='ligada',
        ),
    ]
