# Generated by Django 4.1.4 on 2023-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0002_alter_voto_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='partido',
            field=models.CharField(max_length=10),
        ),
    ]
