# Generated by Django 4.1.4 on 2023-01-27 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0002_urna_data-de-hoje'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__lte', datetime.time(23, 0))), name='hora_fim_limite'),
        ),
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lte', datetime.time(22, 55))), name='hora_inicio_limite'),
        ),
    ]
