# Generated by Django 4.1.4 on 2023-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0004_remove_urna_data-de-hoje_urna_data-de-hoje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politico',
            name='num_partido',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
