# Generated by Django 4.1.4 on 2023-01-29 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0005_alter_politico_num_partido'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='urna',
            name='hora_fim_limite',
        ),
        migrations.RemoveConstraint(
            model_name='urna',
            name='hora_inicio_limite',
        ),
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__lte', datetime.time(23, 55))), name='hora_fim_limite'),
        ),
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lte', datetime.time(23, 50))), name='hora_inicio_limite'),
        ),
    ]
