# Generated by Django 4.1.4 on 2023-01-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0006_remove_urna_hora_fim_limite_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.UniqueConstraint(fields=('data_votacao', 'hora_inicio', 'hora_fim'), name='data_unica'),
        ),
    ]
