# Generated by Django 4.1.4 on 2023-01-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0007_urna_data_unica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urna',
            name='data_votacao',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='urna',
            name='hora_fim',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='urna',
            name='hora_inicio',
            field=models.TimeField(default=None, null=True),
        ),
    ]
