# Generated by Django 4.1.4 on 2023-01-30 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0008_alter_urna_data_votacao_alter_urna_hora_fim_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='urna',
            name='data-de-hoje',
        ),
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao', datetime.date(2023, 1, 30))), name='data-de-hoje'),
        ),
    ]
