# Generated by Django 4.1.4 on 2023-01-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0009_remove_urna_data-de-hoje_urna_data-de-hoje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urna',
            name='data_votacao',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='urna',
            name='hora_fim',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='urna',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
