# Generated by Django 4.1.4 on 2023-01-30 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0011_remove_urna_data-de-hoje'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao', datetime.date(2023, 1, 30))), name='data-de-hoje'),
        ),
    ]
