# Generated by Django 4.1.4 on 2023-02-02 00:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0013_resultado_remove_urna_data-de-hoje_urna_data-de-hoje_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resultado',
            name='votos_validos',
        ),
        migrations.RemoveConstraint(
            model_name='urna',
            name='data-de-hoje',
        ),
        migrations.AddField(
            model_name='resultado',
            name='ausentes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='votos_branco',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='votos_nulo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voto',
            name='eleitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.eleitor'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='politico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.politico'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='urna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.urna'),
        ),
        migrations.AddConstraint(
            model_name='politico',
            constraint=models.UniqueConstraint(fields=('politico', 'partido', 'num_partido', 'cargo'), name='politico_unico'),
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.CheckConstraint(check=models.Q(('votos_invalidos', django.db.models.expressions.CombinedExpression(models.F('votos_branco'), '+', models.F('votos_nulo')))), name='total_invalidos'),
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.CheckConstraint(check=models.Q(('votos_validos', django.db.models.expressions.CombinedExpression(models.F('votos_candidato_A'), '+', models.F('votos_candidato_B')))), name='total_validos'),
        ),
        migrations.AddConstraint(
            model_name='urna',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao', datetime.date(2023, 2, 1))), name='data-de-hoje'),
        ),
    ]
