# Generated by Django 4.1.4 on 2023-02-02 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0014_remove_resultado_votos_validos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_votacao', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='urna',
            name='urna_unica',
        ),
        migrations.RemoveConstraint(
            model_name='urna',
            name='hora_fim_maior',
        ),
        migrations.RemoveConstraint(
            model_name='urna',
            name='hora_fim_limite',
        ),
        migrations.RemoveConstraint(
            model_name='urna',
            name='hora_inicio_limite',
        ),
        migrations.RemoveConstraint(
            model_name='urna',
            name='data_unica',
        ),
        migrations.RemoveConstraint(
            model_name='urna',
            name='data-de-hoje',
        ),
        migrations.RemoveField(
            model_name='urna',
            name='data_votacao',
        ),
        migrations.RemoveField(
            model_name='urna',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='urna',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='datavotacao',
            name='urna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datas', to='urna.urna'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='hora_fim_maior'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__lte', datetime.time(23, 55))), name='hora_fim_limite'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lte', datetime.time(23, 50))), name='hora_inicio_limite'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao', datetime.date(2023, 2, 2))), name='data-de-hoje'),
        ),
    ]
