# Generated by Django 4.1.4 on 2023-02-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0015_datavotacao_remove_urna_urna_unica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavotacao',
            name='data_votacao',
            field=models.DateField(unique=True),
        ),
    ]
