# Generated by Django 4.1.4 on 2023-02-03 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0016_alter_datavotacao_data_votacao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datavotacao',
            name='data-de-hoje',
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao', datetime.date(2023, 2, 3))), name='data-de-hoje'),
        ),
    ]
