# Generated by Django 4.1.4 on 2023-02-04 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0017_remove_datavotacao_data-de-hoje_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datavotacao',
            name='data-de-hoje',
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao', datetime.date(2023, 2, 4))), name='data-de-hoje'),
        ),
    ]
