# Generated by Django 4.1.4 on 2023-02-06 21:54

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0019_remove_datavotacao_hora_fim_maior_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datavotacao',
            name='hora_fim_maior',
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__lte', django.db.models.expressions.CombinedExpression(models.F('hora_inicio'), '+', models.Value(datetime.time(0, 10))))), name='hora_fim_maximo'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__gte', django.db.models.expressions.CombinedExpression(models.F('hora_inicio'), '+', models.Value(datetime.time(0, 5))))), name='hora_fim_minimo'),
        ),
    ]
