# Generated by Django 4.1.4 on 2023-02-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0021_remove_datavotacao_hora_fim_maximo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datavotacao',
            name='hora_fim_minimo',
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='hora_fim_maior'),
        ),
    ]
