# Generated by Django 4.1.4 on 2023-02-07 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0022_remove_datavotacao_hora_fim_minimo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao__gte', datetime.date(2023, 2, 7))), name='data-de-hoje'),
        ),
    ]
