# Generated by Django 4.1.4 on 2023-02-07 22:21

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0023_datavotacao_data-de-hoje'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datavotacao',
            name='hora_fim_maior',
        ),
        migrations.RemoveConstraint(
            model_name='datavotacao',
            name='data-de-hoje',
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('data_votacao__gte', datetime.date(2023, 2, 7))), name='data_maior_ou_igual_hoje'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__lte', django.db.models.expressions.CombinedExpression(models.F('hora_inicio'), '+', models.Value(datetime.timedelta(seconds=600))))), name='hora_fim_menor_ou_igual_dez_min'),
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__gte', django.db.models.expressions.CombinedExpression(models.F('hora_inicio'), '+', models.Value(datetime.timedelta(seconds=300))))), name='hora_fim_maior_ou_igual_cinco_min'),
        ),
    ]
