# Generated by Django 4.1.4 on 2023-02-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0024_remove_datavotacao_hora_fim_maior_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datavotacao',
            name='hora_fim_menor_ou_igual_dez_min',
        ),
        migrations.RemoveConstraint(
            model_name='datavotacao',
            name='hora_fim_maior_ou_igual_cinco_min',
        ),
        migrations.AddConstraint(
            model_name='datavotacao',
            constraint=models.CheckConstraint(check=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='hora_fim_maior_inicio'),
        ),
    ]
