# Generated by Django 4.1.4 on 2023-02-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0025_remove_datavotacao_hora_fim_menor_ou_igual_dez_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='total_eleitores',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
