# Generated by Django 4.1.4 on 2022-12-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('foto', models.ImageField(height_field=128, upload_to='', width_field=128)),
                ('cargo', models.CharField(max_length=50)),
                ('partido', models.CharField(max_length=50)),
                ('num_partido', models.CharField(max_length=2)),
                ('urna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='politicos', to='urna.urna')),
            ],
        ),
    ]
