# Generated by Django 4.1.4 on 2022-12-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politico', '0002_alter_politico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politico',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
