# Generated by Django 4.1.4 on 2022-12-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleitor',
            name='titulo_eleitor',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
