# Generated by Django 4.1.4 on 2023-01-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleitor',
            options={'verbose_name_plural': 'Eleitores'},
        ),
    ]
